# Development profile
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    wfederico.backendjavacoretemplate: DEBUG
    org.hibernate.SQL: DEBUG

